name: Feature or Model Request
description: Request a new econometric model, estimation method, or feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature or model. Please provide enough detail so we can evaluate and plan the implementation.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of addition is this?
      options:
        - New econometric model
        - New estimation method for existing model
        - New identification scheme
        - New hypothesis test or diagnostic
        - New built-in dataset
        - API improvement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature or model you would like added.
      placeholder: |
        Example: "Add Threshold VAR (TVAR) estimation with Hansen (1996) linearity test."
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Key papers or textbooks. Include author, year, and DOI/ISBN if available.
      placeholder: |
        - Hansen, B. E. (1996). "Inference When a Nuisance Parameter Is Not Identified Under the Null Hypothesis." Econometrica, 64(2), 413-430. DOI: 10.2307/2171789
    validations:
      required: false

  - type: textarea
    id: api
    attributes:
      label: Suggested API
      description: Optional. What might the user-facing function calls look like?
      render: julia
      placeholder: |
        m = estimate_tvar(Y, p; threshold_var=1, trim=0.15)
        irf(m, H; regime=1)
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Why is this useful? Any related issues or PRs?
    validations:
      required: false
